FROM mariadb:latest

# Configuration du mot de passe par défaut
ENV MYSQL_ROOT_PASSWORD=root

# Copier un script d'initialisation SQL dans le dossier d'initialisation
COPY /docker-entrypoint-initdb.d/
